create table empresa (
	id INT,
	company VARCHAR(50),
	address VARCHAR(50)
);
insert into empresa (id, company, address) values (1, 'Aivee', '9428 Sage Way');
insert into empresa (id, company, address) values (2, 'Eidel', '73344 Graceland Alley');
insert into empresa (id, company, address) values (3, 'Aimbu', '33 Menomonie Junction');
insert into empresa (id, company, address) values (4, 'Viva', '592 Veith Junction');
insert into empresa (id, company, address) values (5, 'Edgewire', '808 Dorton Terrace');
insert into empresa (id, company, address) values (6, 'Rhycero', '6160 Bunting Alley');
insert into empresa (id, company, address) values (7, 'JumpXS', '671 Talmadge Avenue');
insert into empresa (id, company, address) values (8, 'Youspan', '669 Jackson Crossing');
insert into empresa (id, company, address) values (9, 'Minyx', '9787 Caliangt Park');
insert into empresa (id, company, address) values (10, 'Yamia', '6085 Division Lane');
insert into empresa (id, company, address) values (11, 'Skinix', '5956 Colorado Parkway');
insert into empresa (id, company, address) values (12, 'Camimbo', '60274 Burning Wood Junction');
insert into empresa (id, company, address) values (13, 'Divape', '115 Mallard Circle');
insert into empresa (id, company, address) values (14, 'Tazz', '60358 Arizona Terrace');
insert into empresa (id, company, address) values (15, 'Flipbug', '01064 Hermina Pass');
insert into empresa (id, company, address) values (16, 'Jabbersphere', '4941 Linden Court');
insert into empresa (id, company, address) values (17, 'Dynava', '63 Sage Place');
insert into empresa (id, company, address) values (18, 'Quire', '93 Blue Bill Park Drive');
insert into empresa (id, company, address) values (19, 'Browsecat', '85572 Lunder Court');
insert into empresa (id, company, address) values (20, 'Edgepulse', '7348 Kennedy Drive');
insert into empresa (id, company, address) values (21, 'Thoughtbridge', '7 Cambridge Crossing');
insert into empresa (id, company, address) values (22, 'Quimba', '63 Paget Junction');
insert into empresa (id, company, address) values (23, 'Teklist', '5 Amoth Place');
insert into empresa (id, company, address) values (24, 'Minyx', '5343 Lindbergh Center');
insert into empresa (id, company, address) values (25, 'Jabberstorm', '69059 Grim Terrace');
insert into empresa (id, company, address) values (26, 'Topicblab', '916 Corben Point');
insert into empresa (id, company, address) values (27, 'Pixoboo', '3540 Muir Point');
insert into empresa (id, company, address) values (28, 'Voonte', '969 Vera Center');
insert into empresa (id, company, address) values (29, 'Skiba', '504 Scoville Drive');
insert into empresa (id, company, address) values (30, 'Bubbletube', '86 Roth Pass');
insert into empresa (id, company, address) values (31, 'Divavu', '33904 Moulton Parkway');
insert into empresa (id, company, address) values (32, 'LiveZ', '8514 Welch Pass');
insert into empresa (id, company, address) values (33, 'Shuffletag', '87 Anhalt Junction');
insert into empresa (id, company, address) values (34, 'Yotz', '556 Manufacturers Lane');
insert into empresa (id, company, address) values (35, 'Skyba', '819 Service Trail');
insert into empresa (id, company, address) values (36, 'Twitterbeat', '27628 Oriole Road');
insert into empresa (id, company, address) values (37, 'Gabtune', '464 Melrose Crossing');
insert into empresa (id, company, address) values (38, 'Fliptune', '137 Sloan Lane');
insert into empresa (id, company, address) values (39, 'Babbleblab', '5 Helena Point');
insert into empresa (id, company, address) values (40, 'Browsebug', '67706 Crest Line Way');
insert into empresa (id, company, address) values (41, 'Topicware', '06109 Bayside Junction');
insert into empresa (id, company, address) values (42, 'Dynazzy', '586 Talisman Alley');
insert into empresa (id, company, address) values (43, 'Feedmix', '9 Fordem Drive');
insert into empresa (id, company, address) values (44, 'Dazzlesphere', '806 Clarendon Hill');
insert into empresa (id, company, address) values (45, 'Plambee', '80129 Burning Wood Plaza');
insert into empresa (id, company, address) values (46, 'Flashpoint', '78 Moose Hill');
insert into empresa (id, company, address) values (47, 'Bluejam', '02 Cambridge Street');
insert into empresa (id, company, address) values (48, 'Devify', '76 Kinsman Plaza');
insert into empresa (id, company, address) values (49, 'Oloo', '03 4th Lane');
insert into empresa (id, company, address) values (50, 'Yoveo', '82 5th Street');
insert into empresa (id, company, address) values (51, 'Zoozzy', '8825 Lillian Avenue');
insert into empresa (id, company, address) values (52, 'Yodoo', '1 Barnett Court');
insert into empresa (id, company, address) values (53, 'Jabberbean', '441 Service Plaza');
insert into empresa (id, company, address) values (54, 'Twitterbeat', '49 Arkansas Way');
insert into empresa (id, company, address) values (55, 'Quaxo', '60 Schurz Circle');
insert into empresa (id, company, address) values (56, 'Shufflester', '59 Mallard Place');
insert into empresa (id, company, address) values (57, 'Zoomlounge', '7443 Reindahl Place');
insert into empresa (id, company, address) values (58, 'Brightbean', '37082 Nevada Junction');
insert into empresa (id, company, address) values (59, 'Zoomzone', '4356 Fairview Park');
insert into empresa (id, company, address) values (60, 'Gabtype', '199 Longview Trail');
insert into empresa (id, company, address) values (61, 'Pixope', '78380 Rockefeller Place');
insert into empresa (id, company, address) values (62, 'Vidoo', '1743 Burrows Plaza');
insert into empresa (id, company, address) values (63, 'Meembee', '70323 Swallow Park');
insert into empresa (id, company, address) values (64, 'Skynoodle', '68 Gerald Hill');
insert into empresa (id, company, address) values (65, 'Aibox', '488 Nevada Terrace');
insert into empresa (id, company, address) values (66, 'Devpulse', '95 Pennsylvania Drive');
insert into empresa (id, company, address) values (67, 'Twitterwire', '0 Daystar Lane');
insert into empresa (id, company, address) values (68, 'Leenti', '83 Everett Parkway');
insert into empresa (id, company, address) values (69, 'Yabox', '080 Stephen Alley');
insert into empresa (id, company, address) values (70, 'Kwilith', '362 Havey Point');
insert into empresa (id, company, address) values (71, 'Zoozzy', '948 Hanover Parkway');
insert into empresa (id, company, address) values (72, 'Voonix', '77 Claremont Lane');
insert into empresa (id, company, address) values (73, 'Chatterpoint', '06639 Glacier Hill Drive');
insert into empresa (id, company, address) values (74, 'Tagtune', '5823 Fisk Place');
insert into empresa (id, company, address) values (75, 'LiveZ', '22 Homewood Point');
insert into empresa (id, company, address) values (76, 'Oyoba', '758 Commercial Way');
insert into empresa (id, company, address) values (77, 'Viva', '04 Pine View Drive');
insert into empresa (id, company, address) values (78, 'Shufflester', '92 Victoria Crossing');
insert into empresa (id, company, address) values (79, 'Twiyo', '07884 Dapin Drive');
insert into empresa (id, company, address) values (80, 'Eidel', '8 Troy Drive');
insert into empresa (id, company, address) values (81, 'Riffpath', '275 Sunfield Terrace');
insert into empresa (id, company, address) values (82, 'LiveZ', '77 Pearson Hill');
insert into empresa (id, company, address) values (83, 'Gigashots', '44 David Street');
insert into empresa (id, company, address) values (84, 'Babbleopia', '40 Spohn Lane');
insert into empresa (id, company, address) values (85, 'Browsezoom', '5 Huxley Parkway');
insert into empresa (id, company, address) values (86, 'Edgetag', '978 Oak Valley Drive');
insert into empresa (id, company, address) values (87, 'Realblab', '5 Park Meadow Place');
insert into empresa (id, company, address) values (88, 'Camido', '77 Longview Circle');
insert into empresa (id, company, address) values (89, 'Riffpath', '91500 8th Drive');
insert into empresa (id, company, address) values (90, 'Thoughtmix', '0235 Nancy Center');
insert into empresa (id, company, address) values (91, 'Ooba', '68 Judy Way');
insert into empresa (id, company, address) values (92, 'Skalith', '42146 Graedel Plaza');
insert into empresa (id, company, address) values (93, 'Teklist', '88 Mccormick Junction');
insert into empresa (id, company, address) values (94, 'Babbleopia', '97224 Michigan Court');
insert into empresa (id, company, address) values (95, 'Pixope', '8 Jenifer Hill');
insert into empresa (id, company, address) values (96, 'Fanoodle', '486 American Crossing');
insert into empresa (id, company, address) values (97, 'Skyble', '4808 Comanche Center');
insert into empresa (id, company, address) values (98, 'Youopia', '41007 Prentice Point');
insert into empresa (id, company, address) values (99, 'Edgeclub', '96 Melrose Trail');
insert into empresa (id, company, address) values (100, 'Yodoo', '02854 4th Junction');
insert into empresa (id, company, address) values (500, 'Browsedrive', '355 Hansons Street');
insert into empresa (id, company, address) values (501, 'Fivespan', '3 Fordem Avenue');
insert into empresa (id, company, address) values (502, 'Realbuzz', '4 Westport Pass');
insert into empresa (id, company, address) values (503, 'Kwilith', '66084 Linden Street');
insert into empresa (id, company, address) values (504, 'Fiveclub', '37 New Castle Plaza');
insert into empresa (id, company, address) values (505, 'Mybuzz', '23424 Haas Junction');
insert into empresa (id, company, address) values (506, 'Eimbee', '66318 Acker Circle');
insert into empresa (id, company, address) values (507, 'Realfire', '79 Sunnyside Plaza');
insert into empresa (id, company, address) values (508, 'Dabtype', '03891 Armistice Lane');
insert into empresa (id, company, address) values (509, 'Quinu', '6 Oakridge Parkway');
insert into empresa (id, company, address) values (510, 'Leenti', '4 Badeau Parkway');
insert into empresa (id, company, address) values (511, 'Lazzy', '440 Hayes Court');
insert into empresa (id, company, address) values (512, 'LiveZ', '61 Hazelcrest Pass');
insert into empresa (id, company, address) values (513, 'Fatz', '0925 Troy Court');
insert into empresa (id, company, address) values (514, 'Ozu', '10 Fuller Way');
insert into empresa (id, company, address) values (515, 'Devcast', '8 Morning Avenue');
insert into empresa (id, company, address) values (516, 'Rhycero', '9 Lunder Road');
insert into empresa (id, company, address) values (517, 'Topdrive', '7 Kipling Trail');
insert into empresa (id, company, address) values (518, 'Ntag', '6002 Hintze Pass');
insert into empresa (id, company, address) values (519, 'Realpoint', '97382 Autumn Leaf Terrace');
insert into empresa (id, company, address) values (520, 'Skiba', '421 Lunder Trail');
insert into empresa (id, company, address) values (521, 'Oyondu', '910 Arizona Alley');
insert into empresa (id, company, address) values (522, 'Ntag', '79 Di Loreto Avenue');
insert into empresa (id, company, address) values (523, 'Rhynyx', '989 Erie Junction');
insert into empresa (id, company, address) values (524, 'Gabcube', '58 Vermont Center');
insert into empresa (id, company, address) values (525, 'Babbleopia', '6399 Di Loreto Trail');
insert into empresa (id, company, address) values (526, 'Jayo', '80 Badeau Lane');
insert into empresa (id, company, address) values (527, 'Divape', '67184 Thierer Way');
insert into empresa (id, company, address) values (528, 'Jatri', '6 Bartelt Alley');
insert into empresa (id, company, address) values (529, 'Thoughtbeat', '5 Hooker Street');
insert into empresa (id, company, address) values (530, 'Gabtype', '3 North Place');
insert into empresa (id, company, address) values (531, 'Tagfeed', '7691 Amoth Road');
insert into empresa (id, company, address) values (532, 'Zoomlounge', '11 Russell Plaza');
insert into empresa (id, company, address) values (533, 'Feedspan', '295 Vermont Center');
insert into empresa (id, company, address) values (534, 'Oozz', '05 Amoth Avenue');
insert into empresa (id, company, address) values (535, 'Lajo', '553 Sage Hill');
insert into empresa (id, company, address) values (536, 'Wikivu', '0 South Trail');
insert into empresa (id, company, address) values (537, 'Pixoboo', '8 Lotheville Way');
insert into empresa (id, company, address) values (538, 'Eire', '46 Coleman Circle');
insert into empresa (id, company, address) values (539, 'Abatz', '03 Veith Place');
insert into empresa (id, company, address) values (540, 'Jaloo', '50208 Vermont Terrace');
insert into empresa (id, company, address) values (541, 'Skynoodle', '59 Aberg Trail');
insert into empresa (id, company, address) values (542, 'Realpoint', '26309 Crowley Plaza');
insert into empresa (id, company, address) values (543, 'Jabberbean', '7964 Southridge Way');
insert into empresa (id, company, address) values (544, 'Brightbean', '252 Lerdahl Pass');
insert into empresa (id, company, address) values (545, 'Trilith', '09273 Luster Crossing');
insert into empresa (id, company, address) values (546, 'Quire', '5 Washington Hill');
insert into empresa (id, company, address) values (547, 'Browsedrive', '895 Hanover Point');
insert into empresa (id, company, address) values (548, 'Babbleopia', '76551 Morning Point');
insert into empresa (id, company, address) values (549, 'Mynte', '429 Johnson Parkway');
insert into empresa (id, company, address) values (550, 'Twitternation', '20 Brickson Park Junction');
insert into empresa (id, company, address) values (551, 'Centizu', '4 Butternut Circle');
insert into empresa (id, company, address) values (552, 'Devbug', '6357 Village Green Court');
insert into empresa (id, company, address) values (553, 'Devbug', '2 Clemons Lane');
insert into empresa (id, company, address) values (554, 'Linkbuzz', '13067 Buena Vista Hill');
insert into empresa (id, company, address) values (555, 'Edgeclub', '6085 Pawling Point');
insert into empresa (id, company, address) values (556, 'Fiveclub', '3 Eagan Pass');
insert into empresa (id, company, address) values (557, 'Dazzlesphere', '93 Eagan Lane');
insert into empresa (id, company, address) values (558, 'Zoomdog', '67 Walton Park');
insert into empresa (id, company, address) values (559, 'Thoughtstorm', '2 Anderson Court');
insert into empresa (id, company, address) values (560, 'Vidoo', '229 Anthes Trail');
insert into empresa (id, company, address) values (561, 'Oloo', '3 Delladonna Place');
insert into empresa (id, company, address) values (562, 'Babblestorm', '78854 Manufacturers Court');
insert into empresa (id, company, address) values (563, 'Gabvine', '7 Eagle Crest Hill');
insert into empresa (id, company, address) values (564, 'Youspan', '6 Truax Terrace');
insert into empresa (id, company, address) values (565, 'Tambee', '7 Sheridan Trail');
insert into empresa (id, company, address) values (566, 'Demizz', '80288 Ridge Oak Street');
insert into empresa (id, company, address) values (567, 'Kanoodle', '3581 Kipling Trail');
insert into empresa (id, company, address) values (568, 'JumpXS', '4 Summer Ridge Pass');
insert into empresa (id, company, address) values (569, 'Mudo', '7186 Eagle Crest Junction');
insert into empresa (id, company, address) values (570, 'Fanoodle', '120 Linden Point');
insert into empresa (id, company, address) values (571, 'Yombu', '93 Havey Trail');
insert into empresa (id, company, address) values (572, 'Meetz', '03 Eastlawn Court');
insert into empresa (id, company, address) values (573, 'Linkbridge', '18112 Grayhawk Pass');
insert into empresa (id, company, address) values (574, 'Katz', '4630 Arkansas Junction');
insert into empresa (id, company, address) values (575, 'Photobug', '3 Vidon Way');
insert into empresa (id, company, address) values (576, 'Kayveo', '52768 Oak Valley Center');
insert into empresa (id, company, address) values (577, 'Feedspan', '7 Carberry Street');
insert into empresa (id, company, address) values (578, 'Browsecat', '605 Glendale Road');
insert into empresa (id, company, address) values (579, 'Wikivu', '9699 Laurel Circle');
insert into empresa (id, company, address) values (580, 'Demizz', '947 Thompson Crossing');
insert into empresa (id, company, address) values (581, 'Flashdog', '3206 Arapahoe Lane');
insert into empresa (id, company, address) values (582, 'Abata', '2591 Crest Line Avenue');
insert into empresa (id, company, address) values (583, 'Leenti', '0 Morning Point');
insert into empresa (id, company, address) values (584, 'Viva', '851 Rowland Circle');
insert into empresa (id, company, address) values (585, 'Jabbertype', '51 Lindbergh Parkway');
insert into empresa (id, company, address) values (586, 'Topicstorm', '22665 Express Drive');
insert into empresa (id, company, address) values (587, 'Quimm', '25 Sachs Place');
insert into empresa (id, company, address) values (588, 'Myworks', '2 Nova Plaza');
insert into empresa (id, company, address) values (589, 'Oyoloo', '60 Havey Terrace');
insert into empresa (id, company, address) values (590, 'Oloo', '92 Myrtle Alley');
insert into empresa (id, company, address) values (591, 'Lajo', '38 Sachs Crossing');
insert into empresa (id, company, address) values (592, 'Kwilith', '87916 Ilene Avenue');
insert into empresa (id, company, address) values (593, 'Chatterbridge', '38 Anthes Court');
insert into empresa (id, company, address) values (594, 'Skalith', '2 Carberry Point');
insert into empresa (id, company, address) values (595, 'Buzzshare', '5363 Washington Trail');
insert into empresa (id, company, address) values (596, 'Voolia', '0396 Morrow Crossing');
insert into empresa (id, company, address) values (597, 'Skalith', '3278 3rd Trail');
insert into empresa (id, company, address) values (598, 'InnoZ', '85 American Drive');
insert into empresa (id, company, address) values (599, 'Yamia', '52 Kropf Place');
insert into empresa (id, company, address) values (600, 'Jetpulse', '11 Mandrake Plaza');
insert into empresa (id, company, address) values (601, 'Fivechat', '78550 Starling Drive');
insert into empresa (id, company, address) values (602, 'Babblestorm', '85967 Hudson Parkway');
insert into empresa (id, company, address) values (603, 'Browseblab', '4635 Lakewood Avenue');
insert into empresa (id, company, address) values (604, 'Cogilith', '83 Everett Terrace');
insert into empresa (id, company, address) values (605, 'Wordify', '512 Huxley Plaza');
insert into empresa (id, company, address) values (606, 'Shuffletag', '32991 Vernon Street');
insert into empresa (id, company, address) values (607, 'Dabjam', '4936 Lake View Road');
insert into empresa (id, company, address) values (608, 'Browsebug', '56786 Del Mar Street');
insert into empresa (id, company, address) values (609, 'Devcast', '65 Westport Center');
insert into empresa (id, company, address) values (610, 'Skipstorm', '2 Barnett Circle');
insert into empresa (id, company, address) values (611, 'Jatri', '65 Monterey Point');
insert into empresa (id, company, address) values (612, 'Tekfly', '900 3rd Terrace');
insert into empresa (id, company, address) values (613, 'Realblab', '706 Towne Court');
insert into empresa (id, company, address) values (614, 'Skibox', '1 Pawling Alley');
insert into empresa (id, company, address) values (615, 'Jaxnation', '60029 Prairie Rose Circle');
insert into empresa (id, company, address) values (616, 'Shufflester', '58445 Pepper Wood Court');
insert into empresa (id, company, address) values (617, 'Topiclounge', '25450 Hollow Ridge Place');
insert into empresa (id, company, address) values (618, 'Realpoint', '911 Lukken Plaza');
insert into empresa (id, company, address) values (619, 'Snaptags', '7538 American Circle');
insert into empresa (id, company, address) values (620, 'Quimm', '50921 Hintze Plaza');
insert into empresa (id, company, address) values (621, 'Jetpulse', '3 Red Cloud Street');
insert into empresa (id, company, address) values (622, 'Linklinks', '5 Crest Line Court');
insert into empresa (id, company, address) values (623, 'Skippad', '5 Cordelia Road');
insert into empresa (id, company, address) values (624, 'Camimbo', '843 Michigan Alley');
insert into empresa (id, company, address) values (625, 'Vipe', '207 Northview Park');
insert into empresa (id, company, address) values (626, 'Gigabox', '684 Milwaukee Street');
insert into empresa (id, company, address) values (627, 'Centizu', '69189 Iowa Terrace');
insert into empresa (id, company, address) values (628, 'Dynabox', '586 Crest Line Crossing');
insert into empresa (id, company, address) values (629, 'Avamm', '0 Harper Center');
insert into empresa (id, company, address) values (630, 'Zoonder', '41185 Lukken Avenue');
insert into empresa (id, company, address) values (631, 'Meetz', '17 Blue Bill Park Way');
insert into empresa (id, company, address) values (632, 'Devshare', '897 Shelley Junction');
insert into empresa (id, company, address) values (633, 'Flashset', '89248 Debs Pass');
insert into empresa (id, company, address) values (634, 'Tagchat', '192 Charing Cross Crossing');
insert into empresa (id, company, address) values (635, 'Oodoo', '3646 Arapahoe Terrace');
insert into empresa (id, company, address) values (636, 'Skyndu', '155 Crest Line Circle');
insert into empresa (id, company, address) values (637, 'Mycat', '0 Petterle Way');
insert into empresa (id, company, address) values (638, 'Bluezoom', '582 8th Center');
insert into empresa (id, company, address) values (639, 'Zooveo', '97 Transport Hill');
insert into empresa (id, company, address) values (640, 'Teklist', '6 Warner Trail');
insert into empresa (id, company, address) values (641, 'Babbleblab', '00 Linden Lane');
insert into empresa (id, company, address) values (642, 'Zoonder', '71054 Lukken Court');
insert into empresa (id, company, address) values (643, 'Jabberbean', '8581 Meadow Valley Street');
insert into empresa (id, company, address) values (644, 'Izio', '8956 Goodland Way');
insert into empresa (id, company, address) values (645, 'Blogspan', '4 Buell Trail');
insert into empresa (id, company, address) values (646, 'Riffpath', '9 Caliangt Lane');
insert into empresa (id, company, address) values (647, 'Voonyx', '16650 Green Ridge Way');
insert into empresa (id, company, address) values (648, 'Twitternation', '78 Scott Circle');
insert into empresa (id, company, address) values (649, 'Skiba', '75402 Prentice Avenue');
insert into empresa (id, company, address) values (650, 'Yakidoo', '13064 Superior Circle');
insert into empresa (id, company, address) values (651, 'Flashpoint', '1662 Oneill Crossing');
insert into empresa (id, company, address) values (652, 'Jabberstorm', '39137 American Pass');
insert into empresa (id, company, address) values (653, 'Zoomlounge', '0999 Colorado Circle');
insert into empresa (id, company, address) values (654, 'Edgeclub', '7 Walton Circle');
insert into empresa (id, company, address) values (655, 'Devcast', '554 Lillian Street');
insert into empresa (id, company, address) values (656, 'Quire', '553 Kenwood Road');
insert into empresa (id, company, address) values (657, 'Trilia', '62200 Hazelcrest Plaza');
insert into empresa (id, company, address) values (658, 'Skipfire', '0 Pepper Wood Hill');
insert into empresa (id, company, address) values (659, 'Gigazoom', '865 Mitchell Park');
insert into empresa (id, company, address) values (660, 'Yabox', '75005 Dovetail Place');
insert into empresa (id, company, address) values (661, 'Edgeify', '38 Briar Crest Street');
insert into empresa (id, company, address) values (662, 'Jayo', '8085 Corben Junction');
insert into empresa (id, company, address) values (663, 'Yozio', '79510 Shelley Court');
insert into empresa (id, company, address) values (664, 'Browsezoom', '98 6th Plaza');
insert into empresa (id, company, address) values (665, 'Mydeo', '1968 Mayer Junction');
insert into empresa (id, company, address) values (666, 'Fivespan', '78199 Sutherland Trail');
insert into empresa (id, company, address) values (667, 'Quimba', '11286 Thierer Plaza');
insert into empresa (id, company, address) values (668, 'Centimia', '09 Morningstar Place');
insert into empresa (id, company, address) values (669, 'Meemm', '129 Village Crossing');
insert into empresa (id, company, address) values (670, 'Browsedrive', '43783 Summit Road');
insert into empresa (id, company, address) values (671, 'Dabjam', '81 Pearson Lane');
insert into empresa (id, company, address) values (672, 'Kwimbee', '6614 Carpenter Place');
insert into empresa (id, company, address) values (673, 'Centidel', '404 Manufacturers Hill');
insert into empresa (id, company, address) values (674, 'Babbleset', '0 Heffernan Alley');
insert into empresa (id, company, address) values (675, 'Jabbersphere', '64475 Carey Crossing');
insert into empresa (id, company, address) values (676, 'Blognation', '08 Veith Way');
insert into empresa (id, company, address) values (677, 'Gabspot', '4596 Katie Road');
insert into empresa (id, company, address) values (678, 'Centizu', '89787 Vera Way');
insert into empresa (id, company, address) values (679, 'Jabbersphere', '7787 Coolidge Road');
insert into empresa (id, company, address) values (680, 'Vinte', '9370 Kings Street');
insert into empresa (id, company, address) values (681, 'Fiveclub', '20 Sullivan Lane');
insert into empresa (id, company, address) values (682, 'Thoughtstorm', '23601 Schlimgen Place');
insert into empresa (id, company, address) values (683, 'Zoonoodle', '4 Fremont Road');
insert into empresa (id, company, address) values (684, 'Ozu', '5276 Canary Alley');
insert into empresa (id, company, address) values (685, 'Quimba', '4623 Kim Parkway');
insert into empresa (id, company, address) values (686, 'Brainsphere', '60 Marquette Parkway');
insert into empresa (id, company, address) values (687, 'Shufflester', '2 Briar Crest Junction');
insert into empresa (id, company, address) values (688, 'Eabox', '5748 Bonner Drive');
insert into empresa (id, company, address) values (689, 'Rhyloo', '1 Kropf Pass');
insert into empresa (id, company, address) values (690, 'Demimbu', '33 Stephen Circle');
insert into empresa (id, company, address) values (691, 'Izio', '84883 Ohio Park');
insert into empresa (id, company, address) values (692, 'Jaxspan', '29 Merrick Plaza');
insert into empresa (id, company, address) values (693, 'Avamm', '82805 Schlimgen Avenue');
insert into empresa (id, company, address) values (694, 'Kimia', '53147 Oak Street');
insert into empresa (id, company, address) values (695, 'Yombu', '75626 Rieder Street');
insert into empresa (id, company, address) values (696, 'Devbug', '7450 Sutteridge Plaza');
insert into empresa (id, company, address) values (697, 'Jaxspan', '98 Lyons Trail');
insert into empresa (id, company, address) values (698, 'Photojam', '089 Hoard Drive');
insert into empresa (id, company, address) values (699, 'Yozio', '366 Trailsway Place');
insert into empresa (id, company, address) values (700, 'Oyonder', '1 Delaware Center');
insert into empresa (id, company, address) values (911, 'Jaxbean', '4141 Claremont Terrace');
insert into empresa (id, company, address) values (912, 'Twinder', '6168 Holy Cross Circle');
insert into empresa (id, company, address) values (913, 'Gabspot', '54 Swallow Avenue');
insert into empresa (id, company, address) values (914, 'Meemm', '78388 Redwing Way');
insert into empresa (id, company, address) values (915, 'Chatterpoint', '0 Laurel Junction');
insert into empresa (id, company, address) values (916, 'Aimbu', '84008 Gina Way');
insert into empresa (id, company, address) values (917, 'Oodoo', '71 Express Pass');
insert into empresa (id, company, address) values (918, 'Blogspan', '41 Ridgeview Lane');
insert into empresa (id, company, address) values (919, 'Skipfire', '3666 Morning Point');
insert into empresa (id, company, address) values (920, 'Skaboo', '903 Prairie Rose Way');
insert into empresa (id, company, address) values (921, 'Twitterwire', '1 Thierer Street');
insert into empresa (id, company, address) values (922, 'Dynazzy', '064 Macpherson Terrace');
insert into empresa (id, company, address) values (923, 'Eabox', '7 Old Gate Junction');
insert into empresa (id, company, address) values (924, 'Geba', '19090 Marquette Terrace');
insert into empresa (id, company, address) values (925, 'InnoZ', '93 Macpherson Drive');
insert into empresa (id, company, address) values (926, 'Gigashots', '74426 Graedel Parkway');
insert into empresa (id, company, address) values (927, 'Wordware', '01481 Elgar Road');
insert into empresa (id, company, address) values (928, 'Gigaclub', '8 Rieder Center');
insert into empresa (id, company, address) values (929, 'Thoughtstorm', '6 Barnett Street');
insert into empresa (id, company, address) values (930, 'Jaxworks', '74142 Goodland Crossing');
insert into empresa (id, company, address) values (931, 'Yoveo', '543 Sunnyside Hill');
insert into empresa (id, company, address) values (932, 'Thoughtworks', '4450 Mesta Avenue');
insert into empresa (id, company, address) values (933, 'Photolist', '629 Ruskin Drive');
insert into empresa (id, company, address) values (934, 'Oyoba', '701 Crest Line Pass');
insert into empresa (id, company, address) values (935, 'Brightbean', '15945 Rieder Circle');
insert into empresa (id, company, address) values (936, 'Kazio', '9366 Ramsey Place');
insert into empresa (id, company, address) values (937, 'Twitterbridge', '142 Hansons Parkway');
insert into empresa (id, company, address) values (938, 'Kwinu', '6 Mockingbird Parkway');
insert into empresa (id, company, address) values (939, 'Babblestorm', '6 Farwell Avenue');
insert into empresa (id, company, address) values (940, 'Realpoint', '6688 Kingsford Avenue');
insert into empresa (id, company, address) values (941, 'Eadel', '939 Lillian Way');
insert into empresa (id, company, address) values (942, 'Skimia', '5289 Washington Place');
insert into empresa (id, company, address) values (943, 'Skalith', '1 Upham Center');
insert into empresa (id, company, address) values (944, 'LiveZ', '49 Briar Crest Center');
insert into empresa (id, company, address) values (945, 'Babblestorm', '0 Gale Road');
insert into empresa (id, company, address) values (946, 'Mita', '9 Coleman Terrace');
insert into empresa (id, company, address) values (947, 'Lajo', '397 Ilene Junction');
insert into empresa (id, company, address) values (948, 'Agivu', '5028 Kennedy Court');
insert into empresa (id, company, address) values (949, 'Rhynyx', '89512 Macpherson Avenue');
insert into empresa (id, company, address) values (950, 'Yakitri', '52 Harbort Pass');
insert into empresa (id, company, address) values (951, 'Oyope', '308 Towne Avenue');
insert into empresa (id, company, address) values (952, 'Quatz', '793 Dennis Place');
insert into empresa (id, company, address) values (953, 'Dablist', '6 Monument Street');
insert into empresa (id, company, address) values (954, 'Voolia', '685 Beilfuss Parkway');
insert into empresa (id, company, address) values (955, 'Thoughtstorm', '9 Ridgeway Place');
insert into empresa (id, company, address) values (956, 'Yambee', '0316 Bluejay Drive');
insert into empresa (id, company, address) values (957, 'Jabberbean', '1196 Pepper Wood Way');
insert into empresa (id, company, address) values (958, 'Realblab', '357 Independence Crossing');
insert into empresa (id, company, address) values (959, 'Shuffledrive', '699 Macpherson Point');
insert into empresa (id, company, address) values (960, 'Tanoodle', '130 Bunker Hill Plaza');
insert into empresa (id, company, address) values (961, 'Voonder', '4699 International Center');
insert into empresa (id, company, address) values (962, 'Demizz', '143 Fairfield Park');
insert into empresa (id, company, address) values (963, 'Avaveo', '49920 Summit Trail');
insert into empresa (id, company, address) values (964, 'Latz', '3 Mariners Cove Avenue');
insert into empresa (id, company, address) values (965, 'Podcat', '7 Artisan Crossing');
insert into empresa (id, company, address) values (966, 'Einti', '83 Moulton Hill');
insert into empresa (id, company, address) values (967, 'Browsecat', '4185 Lindbergh Avenue');
insert into empresa (id, company, address) values (968, 'Ailane', '879 Sullivan Avenue');
insert into empresa (id, company, address) values (969, 'Dynazzy', '76 New Castle Place');
insert into empresa (id, company, address) values (970, 'Ooba', '75 Columbus Center');
insert into empresa (id, company, address) values (971, 'Mydeo', '4581 Sundown Street');
insert into empresa (id, company, address) values (972, 'Linkbuzz', '91021 Oak Pass');
insert into empresa (id, company, address) values (973, 'Jabbertype', '13400 Crescent Oaks Avenue');
insert into empresa (id, company, address) values (974, 'Jabberbean', '7826 Stang Parkway');
insert into empresa (id, company, address) values (975, 'Realblab', '2180 Scoville Hill');
insert into empresa (id, company, address) values (976, 'Tavu', '94104 Karstens Junction');
insert into empresa (id, company, address) values (977, 'Oyondu', '7818 Farmco Parkway');
insert into empresa (id, company, address) values (978, 'Buzzshare', '91 Bashford Court');
insert into empresa (id, company, address) values (979, 'Lajo', '9 Crest Line Lane');
insert into empresa (id, company, address) values (980, 'Fivespan', '7 West Plaza');
insert into empresa (id, company, address) values (981, 'Mydo', '49344 Goodland Hill');
insert into empresa (id, company, address) values (982, 'Zoomzone', '57019 Clyde Gallagher Avenue');
insert into empresa (id, company, address) values (983, 'Eayo', '998 Old Shore Terrace');
insert into empresa (id, company, address) values (984, 'Meejo', '726 Eagan Road');
insert into empresa (id, company, address) values (985, 'Realbuzz', '566 Canary Trail');
insert into empresa (id, company, address) values (986, 'Vipe', '0 Lerdahl Center');
insert into empresa (id, company, address) values (987, 'Centizu', '808 Ridgeway Court');
insert into empresa (id, company, address) values (988, 'Mycat', '98776 Kim Terrace');
insert into empresa (id, company, address) values (989, 'Flashdog', '49 Holy Cross Road');
insert into empresa (id, company, address) values (990, 'Zazio', '0 Ridgeview Park');
insert into empresa (id, company, address) values (991, 'Riffwire', '9215 Melody Way');
insert into empresa (id, company, address) values (992, 'Mymm', '5813 Dahle Court');
insert into empresa (id, company, address) values (993, 'Vipe', '72 Kipling Drive');
insert into empresa (id, company, address) values (994, 'Gevee', '912 New Castle Avenue');
insert into empresa (id, company, address) values (995, 'Meeveo', '67 Dayton Circle');
insert into empresa (id, company, address) values (996, 'Rhyzio', '319 Caliangt Point');
insert into empresa (id, company, address) values (997, 'Yambee', '16721 Moulton Trail');
insert into empresa (id, company, address) values (998, 'Wikibox', '8 Porter Circle');
insert into empresa (id, company, address) values (999, 'Ainyx', '3 Lakewood Alley');
insert into empresa (id, company, address) values (1000, 'Mybuzz', '1615 Westridge Street');
